/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: src/curriculum
 */

// 1. Direct Re-Exports
export * from './curriculumAdapter';
export * from './oakCatalogue';

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: 'src/curriculum',
  timestamp: 1787937755228,
  totalModules: 2,
  exports: [
  {
    "name": "StandardTopic",
    "isType": true,
    "sourceFile": "curriculumAdapter"
  },
  {
    "name": "StandardSubject",
    "isType": true,
    "sourceFile": "curriculumAdapter"
  },
  {
    "name": "StandardStage",
    "isType": true,
    "sourceFile": "curriculumAdapter"
  },
  {
    "name": "adaptOakStage",
    "isType": false,
    "sourceFile": "curriculumAdapter"
  },
  {
    "name": "OakTopic",
    "isType": true,
    "sourceFile": "oakCatalogue"
  },
  {
    "name": "OakSubject",
    "isType": true,
    "sourceFile": "oakCatalogue"
  },
  {
    "name": "OakStage",
    "isType": true,
    "sourceFile": "oakCatalogue"
  },
  {
    "name": "OAK_CURRICULUM_CATALOGUE",
    "isType": false,
    "sourceFile": "oakCatalogue"
  },
  {
    "name": "OakCatalogue",
    "isType": true,
    "sourceFile": "oakCatalogue"
  },
  {
    "name": "DEFAULT_OAK_CATALOGUE",
    "isType": false,
    "sourceFile": "oakCatalogue"
  }
]
} as const;

export type FolderExportNames = 'StandardTopic' | 'StandardSubject' | 'StandardStage' | 'adaptOakStage' | 'OakTopic' | 'OakSubject' | 'OakStage' | 'OAK_CURRICULUM_CATALOGUE' | 'OakCatalogue' | 'DEFAULT_OAK_CATALOGUE';
