/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: src/lib
 */

// 1. Direct Re-Exports
export * from './browser-rag';

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: 'src/lib',
  timestamp: 1787937755144,
  totalModules: 1,
  exports: [
  {
    "name": "RAGMatch",
    "isType": true,
    "sourceFile": "browser-rag"
  },
  {
    "name": "initCurriculumDB",
    "isType": false,
    "sourceFile": "browser-rag"
  },
  {
    "name": "syncCurriculumIndex",
    "isType": false,
    "sourceFile": "browser-rag"
  },
  {
    "name": "searchCurriculum",
    "isType": false,
    "sourceFile": "browser-rag"
  },
  {
    "name": "getLessonManifest",
    "isType": false,
    "sourceFile": "browser-rag"
  }
]
} as const;

export type FolderExportNames = 'RAGMatch' | 'initCurriculumDB' | 'syncCurriculumIndex' | 'searchCurriculum' | 'getLessonManifest';
