import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 Portal Overview',
    },
    {
      type: 'category',
      label: 'Primary (Years 1 - 6)',
      items: [{type: 'autogenerated', dirName: 'primary-years-1-6'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Secondary (Years 7 - 11)',
      items: [{type: 'autogenerated', dirName: 'secondary-years-7-11'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Sixth Form (Years 12 - 14)',
      items: [{type: 'autogenerated', dirName: 'sixth-form-years-12-14'}],
      collapsed: false,
    },
  ],
};

export default sidebars;