// src/engine/astGovernor.ts

export interface RawASTQuestion {
  route?: string;
  scratchpad?: string;
  prompt: string;
  options: string[];
  answerKey: number;
  hint?: string;
  explanation?: string;
  misconceptions?: string[];
  socraticFollowUp?: string;
}

export interface MathCheckupResult {
  isMath: boolean;
  groundTruth: string;
  steps: string[];
  explanation: string;
  isStudentCorrect?: boolean;
}

export interface GovernedQuestion {
  isValid: boolean;
  sanitizedQuestion: (RawASTQuestion & { id?: string }) | null;
  rejectionReason?: string;
}

/**
 * AST Flow Governor: Evaluates, verifies, and sanitizes generated AST trees.
 */
export class ASTFlowGovernor {
  /**
   * Sanitizes the question prompt to strip accidental distractor bleeds,
   * escaped newlines, and trailing choice labels generated by small models.
   */
  public static sanitizePromptText(rawPrompt: string): string {
    if (!rawPrompt) return '';
    let prompt = String(rawPrompt);

    // 1. Strip trailing multiline option lists (e.g. \n\nA) Paris\nB) London...)
    // Only strip if it begins after a newline with an option label and contains multiple option choices
    // or an explicit option block starting with A/1.
    prompt = prompt.replace(/(?:\r?\n|\\n)+\s*(?:[\(\[]?[A-Da-d1-4][\)\]\.\:\-]\s+.*)$/s, (match) => {
      // Check if the match looks like multiple options or has clear option formatting
      if (/(?:[\(\[]?[A-Da-d1-4][\)\]\.\:\-]\s+.*){2,}/s.test(match) || /(?:[\r\n]|\\n)\s*[\(\[]?[B-Db-d2-4][\)\]\.\:\-]/.test(match)) {
        return '';
      }
      // If single line after newline, only strip if it starts with option A or 1
      if (/^[\r\n\s\\]*[\(\[]?[A1a][\)\]\.\:\-]/.test(match)) {
        return '';
      }
      return match;
    });

    // 2. Strip inline option sequence on the same line ONLY if it starts with option A/1 and is followed by B/2
    // e.g. "What is X? A) option1 B) option2 C) option3 D) option4"
    prompt = prompt.replace(/(?:\s+|:\s*)(?:[\(\[]?[Aa1][\)\]\.\:\-])\s+.*?\b(?:[\(\[]?[Bb2][\)\]\.\:\-])\s+.*$/s, '');

    // 3. Strip any lingering escaped newlines
    prompt = prompt.replace(/\\n/g, ' ');

    // 4. Collapse redundant whitespace
    prompt = prompt.replace(/\s+/g, ' ').trim();

    return prompt;
  }

  private static gcd(x: number, y: number): number {
    return !y ? x : this.gcd(y, x % y);
  }

  /**
   * Deterministic Fraction/Decimal/Arithmetic/Unit Solver
   */
  public static verifyArithmetic(rawPrompt: any, rawScratchpad: any = ''): string | null {
    const prompt = String(rawPrompt || '');
    const scratchpad = String(rawScratchpad || '');

    // 1. Decimal to simplest fraction (e.g. "0.6 as a fraction")
    const decToFracMatch = prompt.match(/([\d\.]+)\s+as\s+a\s+fraction/i);
    if (decToFracMatch) {
      const val = parseFloat(decToFracMatch[1]);
      if (!isNaN(val)) {
        const decParts = decToFracMatch[1].split('.');
        const decimalPlaces = decParts[1] ? decParts[1].length : 0;
        const denominator = Math.pow(10, decimalPlaces);
        const numerator = Math.round(val * denominator);

        const divisor = this.gcd(numerator, denominator);
        const simpNum = numerator / divisor;
        const simpDen = denominator / divisor;

        return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
      }
    }

    // 2. Percentage Calculation (e.g. "15% of 80", "What is 20% of 150?")
    const percentMatch = prompt.match(/(\d+(?:\.\d+)?)\s*%\s*(?:of)\s*(\d+(?:\.\d+)?)/i);
    if (percentMatch) {
      const pct = parseFloat(percentMatch[1]);
      const total = parseFloat(percentMatch[2]);
      if (!isNaN(pct) && !isNaN(total)) {
        const result = (pct / 100) * total;
        const formatted = Number.isInteger(result) ? String(result) : String(parseFloat(result.toFixed(2)));
        return formatted;
      }
    }

    // 3. UK National Curriculum Standard Unit Conversions
    const unitConversion = this.evaluateUnitConversion(prompt);
    if (unitConversion !== null) {
      return unitConversion;
    }

    // 4. Fraction Multiplication: (a/b) * (c/d) or a/b * c/d
    const fracMulMatch = prompt.match(/\(?(\d+)\/(\d+)\)?\s*[\*xX×]\s*\(?(\d+)\/(\d+)\)?/);
    if (fracMulMatch) {
      const [, a, b, c, d] = fracMulMatch.map(Number);
      const numerator = a * c;
      const denominator = b * d;

      const divisor = this.gcd(numerator, denominator);
      const simpNum = numerator / divisor;
      const simpDen = denominator / divisor;

      return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
    }

    // 5. Fraction Addition / Subtraction: a/b +/- c/d
    const fracAddMatch = prompt.match(/\(?(\d+)\/(\d+)\)?\s*([\+\-])\s*\(?(\d+)\/(\d+)\)?/);
    if (fracAddMatch) {
      const [, a, b, op, c, d] = fracAddMatch;
      const numA = Number(a), denB = Number(b), numC = Number(c), denD = Number(d);
      const commonDenominator = denB * denD;
      const numerator = op === '+' 
        ? (numA * denD + numC * denB) 
        : (numA * denD - numC * denB);

      const divisor = this.gcd(Math.abs(numerator), commonDenominator);
      const simpNum = numerator / divisor;
      const simpDen = commonDenominator / divisor;

      return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
    }

    // 6. Decimal Division: e.g. "0.5/2"
    const decDivMatch = prompt.match(/([\d\.]+)\s*\/\s*(\d+)/);
    if (decDivMatch) {
      const decVal = parseFloat(decDivMatch[1]);
      const divisorVal = parseInt(decDivMatch[2], 10);
      
      if (!isNaN(decVal) && !isNaN(divisorVal) && divisorVal !== 0) {
        const decParts = decDivMatch[1].split('.');
        const decimalPlaces = decParts[1] ? decParts[1].length : 0;
        const factor = Math.pow(10, decimalPlaces);

        const intNum = Math.round(decVal * factor);
        const intDen = divisorVal * factor;

        const d = this.gcd(intNum, intDen);
        const simpNum = intNum / d;
        const simpDen = intDen / d;

        return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
      }
    }

    // 7. Negative Integers and Two-Operand Arithmetic: e.g. "-4 + (-7)", "7 + -10", "0.75 + 0.25"
    const arithmeticMatch = prompt.match(/(-?\d+(?:\.\d+)?)\s*([\+\-\*\/×÷])\s*\(?(-?\d+(?:\.\d+)?)\)?/);
    if (arithmeticMatch) {
      const num1 = parseFloat(arithmeticMatch[1]);
      let op = arithmeticMatch[2];
      if (op === '×') op = '*';
      if (op === '÷') op = '/';
      const num2 = parseFloat(arithmeticMatch[3]);

      if (!isNaN(num1) && !isNaN(num2)) {
        let result: number | null = null;
        switch (op) {
          case '+': result = num1 + num2; break;
          case '-': result = num1 - num2; break;
          case '*': result = num1 * num2; break;
          case '/': result = num2 !== 0 ? num1 / num2 : null; break;
        }

        if (result !== null) {
          const formatted = Number.isInteger(result) ? String(result) : String(parseFloat(result.toFixed(4)));
          return formatted;
        }
      }
    }

    // 8. BIDMAS / PEMDAS Compound Arithmetic Scratchpad Evaluator
    if (scratchpad) {
      // Look for trailing equality "= 12" or "= 3/4"
      const padEqMatch = scratchpad.match(/=\s*([0-9\.\/%a-zA-Z\s]+)$/);
      if (padEqMatch) {
        return padEqMatch[1].trim();
      }

      // Look for compound arithmetic expression in scratchpad (e.g. "(5 + 3) * 2 = 16")
      const exprMatch = scratchpad.match(/([\d\.\+\-\*\/\(\)\s]{4,})\s*=\s*(-?[\d\.]+)/);
      if (exprMatch) {
        const computed = this.safeEvaluateBIDMAS(exprMatch[1]);
        if (computed !== null) {
          return Number.isInteger(computed) ? String(computed) : String(parseFloat(computed.toFixed(4)));
        }
        return exprMatch[2].trim();
      }
    }

    return null;
  }

  /**
   * Deterministic Evaluator for Standard UK Curriculum Unit Conversions
   */
  private static evaluateUnitConversion(prompt: string): string | null {
    // Length: mm <-> cm, cm <-> m, m <-> km
    const mmToCm = prompt.match(/(\d+(?:\.\d+)?)\s*(?:mm|millimetres|millimeters)\s*(?:to|in|into|as)\s*(?:cm|centimetres|centimeters)/i);
    if (mmToCm) return String(parseFloat((parseFloat(mmToCm[1]) / 10).toFixed(4)));

    const cmToMm = prompt.match(/(\d+(?:\.\d+)?)\s*(?:cm|centimetres|centimeters)\s*(?:to|in|into|as)\s*(?:mm|millimetres|millimeters)/i);
    if (cmToMm) return String(parseFloat((parseFloat(cmToMm[1]) * 10).toFixed(4)));

    const cmToM = prompt.match(/(\d+(?:\.\d+)?)\s*(?:cm|centimetres|centimeters)\s*(?:to|in|into|as)\s*(?:m|metres|meters)/i);
    if (cmToM) return String(parseFloat((parseFloat(cmToM[1]) / 100).toFixed(4)));

    const mToCm = prompt.match(/(\d+(?:\.\d+)?)\s*(?:m|metres|meters)\s*(?:to|in|into|as)\s*(?:cm|centimetres|centimeters)/i);
    if (mToCm) return String(parseFloat((parseFloat(mToCm[1]) * 100).toFixed(4)));

    const mToKm = prompt.match(/(\d+(?:\.\d+)?)\s*(?:m|metres|meters)\s*(?:to|in|into|as)\s*(?:km|kilometres|kilometers)/i);
    if (mToKm) return String(parseFloat((parseFloat(mToKm[1]) / 1000).toFixed(4)));

    const kmToM = prompt.match(/(\d+(?:\.\d+)?)\s*(?:km|kilometres|kilometers)\s*(?:to|in|into|as)\s*(?:m|metres|meters)/i);
    if (kmToM) return String(parseFloat((parseFloat(kmToM[1]) * 1000).toFixed(4)));

    // Mass: g <-> kg
    const gToKg = prompt.match(/(\d+(?:\.\d+)?)\s*(?:g|grams)\s*(?:to|in|into|as)\s*(?:kg|kilograms)/i);
    if (gToKg) return String(parseFloat((parseFloat(gToKg[1]) / 1000).toFixed(4)));

    const kgToG = prompt.match(/(\d+(?:\.\d+)?)\s*(?:kg|kilograms)\s*(?:to|in|into|as)\s*(?:g|grams)/i);
    if (kgToG) return String(parseFloat((parseFloat(kgToG[1]) * 1000).toFixed(4)));

    // Volume: ml <-> l
    const mlToL = prompt.match(/(\d+(?:\.\d+)?)\s*(?:ml|millilitres|milliliters)\s*(?:to|in|into|as)\s*(?:l|litres|liters)/i);
    if (mlToL) return String(parseFloat((parseFloat(mlToL[1]) / 1000).toFixed(4)));

    const lToMl = prompt.match(/(\d+(?:\.\d+)?)\s*(?:l|litres|liters)\s*(?:to|in|into|as)\s*(?:ml|millilitres|milliliters)/i);
    if (lToMl) return String(parseFloat((parseFloat(lToMl[1]) * 1000).toFixed(4)));

    // Currency: £ <-> p
    const poundsToPence = prompt.match(/(?:£|GBP\s*)(\d+(?:\.\d+)?)\s*(?:to|in|into|as)\s*(?:p|pence)/i);
    if (poundsToPence) return String(Math.round(parseFloat(poundsToPence[1]) * 100));

    const penceToPounds = prompt.match(/(\d+)\s*(?:p|pence)\s*(?:to|in|into|as)\s*(?:£|pounds)/i);
    if (penceToPounds) return String(parseFloat((parseFloat(penceToPounds[1]) / 100).toFixed(2)));

    // Time: minutes <-> hours
    const hrsToMins = prompt.match(/(\d+(?:\.\d+)?)\s*(?:hours|hrs)\s*(?:to|in|into|as)\s*(?:minutes|mins)/i);
    if (hrsToMins) return String(parseFloat((parseFloat(hrsToMins[1]) * 60).toFixed(2)));

    const minsToHrs = prompt.match(/(\d+)\s*(?:minutes|mins)\s*(?:to|in|into|as)\s*(?:hours|hrs)/i);
    if (minsToHrs) return String(parseFloat((parseFloat(minsToHrs[1]) / 60).toFixed(2)));

    return null;
  }

  /**
   * Deterministically evaluates mathematical checkup queries and checks student answers.
   * Prevents LLM hallucinations on math checkup queries by providing ground-truth AST evaluation.
   */
  public static evaluateMathCheckup(promptOrQuery: string, secondaryText: string = ''): MathCheckupResult | null {
    const combined = `${promptOrQuery} ${secondaryText}`.trim();
    if (!combined) return null;
    const lower = combined.toLowerCase();

    // 1. Linear Algebraic Equations: e.g. 3x + 7 = 22 or 2x - 4 = 10 or x + 5 = 12
    const linearMatch = combined.match(/(\d*)\s*([a-zA-Z])\s*([\+\-])\s*(\d+)\s*=\s*(\d+)/);
    if (linearMatch) {
      const coeff = linearMatch[1] === '' ? 1 : parseInt(linearMatch[1], 10);
      const variable = linearMatch[2];
      const sign = linearMatch[3];
      const constant = parseInt(linearMatch[4], 10);
      const rhs = parseInt(linearMatch[5], 10);

      const adjustedRhs = sign === '+' ? rhs - constant : rhs + constant;
      const xVal = adjustedRhs / coeff;
      const xStr = Number.isInteger(xVal) ? String(xVal) : String(parseFloat(xVal.toFixed(2)));

      const steps = [
        `Step 1: Perform the inverse operation: ${sign === '+' ? `subtract ${constant}` : `add ${constant}`} from both sides -> ${coeff}${variable} = ${adjustedRhs}.`,
        `Step 2: Divide both sides by ${coeff} -> ${variable} = ${xStr}.`
      ];

      // Check student guess in promptOrQuery
      const studentMatch = promptOrQuery.match(/(?:[a-zA-Z]\s*=\s*|is\s+it\s+|answer\s+is\s+)?(-?\d+(?:\.\d+)?)/i);
      const studentVal = studentMatch ? studentMatch[1] : null;
      const isCorrect = studentVal !== null && Math.abs(parseFloat(studentVal) - xVal) < 0.001;

      return {
        isMath: true,
        groundTruth: `${variable} = ${xStr}`,
        steps,
        explanation: `To solve ${coeff}${variable} ${sign} ${constant} = ${rhs}, isolate ${variable} using inverse operations. ${variable} equals ${xStr}.`,
        isStudentCorrect: studentVal !== null ? isCorrect : undefined,
      };
    }

    // 2. Fractions Addition / Subtraction Concept (e.g. "half a pizza and another quarter", "1/2 + 1/4")
    if (lower.includes('half') && (lower.includes('quarter') || lower.includes('1/4'))) {
      const isSubtraction = lower.includes('take away') || lower.includes('minus') || lower.includes('subtract');
      const groundTruth = isSubtraction ? '1/4' : '3/4';
      const steps = [
        'Step 1: Convert half into quarters using an equivalent fraction: 1/2 = 2/4.',
        isSubtraction
          ? 'Step 2: Subtract the numerators keeping the denominator 4: 2/4 - 1/4 = 1/4.'
          : 'Step 2: Add the numerators keeping the denominator 4: 2/4 + 1/4 = 3/4 (NOT 2/6! You never add denominators).'
      ];
      const hasStudentAns = promptOrQuery.match(/(?:is\s+it\s+|answer\s+is\s+)?([1-4]\/[2-6]|[0-9\.]+)/i);
      const isCorrect = hasStudentAns ? hasStudentAns[1] === groundTruth : undefined;

      return {
        isMath: true,
        groundTruth,
        steps,
        explanation: `1/2 is equivalent to 2/4. When you combine 2/4 with 1/4, you get 3/4. Common trap: never add denominators!`,
        isStudentCorrect: isCorrect,
      };
    }

    // 3. Percentages (e.g. "15% of 80", "20% of 150")
    const pctMatch = combined.match(/(\d+(?:\.\d+)?)\s*%\s*(?:of)\s*(\d+(?:\.\d+)?)/i);
    if (pctMatch) {
      const pct = parseFloat(pctMatch[1]);
      const total = parseFloat(pctMatch[2]);
      const result = (pct / 100) * total;
      const resultStr = Number.isInteger(result) ? String(result) : String(parseFloat(result.toFixed(2)));

      const steps = [
        `Step 1: 10% of ${total} is found by dividing by 10 -> ${total / 10}.`,
        `Step 2: Find 5% by halving 10% -> ${(total / 10) / 2}.`,
        `Step 3: Combine to find ${pct}% of ${total} = ${resultStr}.`
      ];

      const studentMatch = promptOrQuery.match(/(?:is\s+it\s+|answer\s+is\s+)?(-?\d+(?:\.\d+)?)/i);
      const studentVal = studentMatch ? parseFloat(studentMatch[1]) : null;
      const isCorrect = studentVal !== null && Math.abs(studentVal - result) < 0.01;

      return {
        isMath: true,
        groundTruth: resultStr,
        steps,
        explanation: `${pct}% of ${total} is exactly ${resultStr}.`,
        isStudentCorrect: studentVal !== null ? isCorrect : undefined,
      };
    }

    // 4. Place Value / Word Problems: "4 packs of 10 and 3" -> 43
    const packMatch = combined.match(/(\d+)\s+packs?\s+of\s+(\d+)(?:\s+(?:and|\+)\s+(\d+))?/i);
    if (packMatch) {
      const packs = parseInt(packMatch[1], 10);
      const size = parseInt(packMatch[2], 10);
      const extra = packMatch[3] ? parseInt(packMatch[3], 10) : 0;
      const total = packs * size + extra;

      const steps = [
        `Step 1: Multiply the number of packs by pack size: ${packs} × ${size} = ${packs * size}.`,
        extra > 0 ? `Step 2: Add the single extras: ${packs * size} + ${extra} = ${total}.` : `Total = ${total}.`
      ];

      const studentMatch = promptOrQuery.match(/(?:is\s+it\s+|answer\s+is\s+)?(\d+)/i);
      const isCorrect = studentMatch ? parseInt(studentMatch[1], 10) === total : undefined;

      return {
        isMath: true,
        groundTruth: String(total),
        steps,
        explanation: `${packs} packs of ${size} plus ${extra} equals ${total}.`,
        isStudentCorrect: isCorrect,
      };
    }

    // 5. Probability (e.g. "3 red balls and 7 blue balls")
    const probMatch = combined.match(/(\d+)\s+red\s+(?:balls?\s+)?(?:and|\+)\s*(\d+)\s+blue/i);
    if (probMatch) {
      const red = parseInt(probMatch[1], 10);
      const blue = parseInt(probMatch[2], 10);
      const total = red + blue;
      const groundTruth = `${red}/${total}`;

      const steps = [
        `Step 1: Find the total number of outcomes: ${red} red + ${blue} blue = ${total} total.`,
        `Step 2: Probability = favorable outcomes / total outcomes = ${red}/${total} (NOT ${red}/${blue}!).`
      ];

      return {
        isMath: true,
        groundTruth,
        steps,
        explanation: `The probability is favorable outcomes divided by total outcomes: ${red}/${total}.`,
      };
    }

    // 6. Rounding: "350 rounded to nearest hundred" -> 400, "349" -> 300
    const roundMatch = combined.match(/(\d+)\s+rounded\s+to\s+(?:the\s+)?nearest\s+(ten|hundred|thousand)/i);
    if (roundMatch) {
      const num = parseInt(roundMatch[1], 10);
      const unit = roundMatch[2].toLowerCase();
      let factor = 10;
      if (unit === 'hundred') factor = 100;
      if (unit === 'thousand') factor = 1000;
      const rounded = Math.round(num / factor) * factor;

      const steps = [
        `Step 1: Check the digit to the right of the ${unit} place.`,
        `Step 2: 5 or more rounds UP, 4 or less rounds DOWN -> ${num} rounds to ${rounded}.`
      ];

      return {
        isMath: true,
        groundTruth: String(rounded),
        steps,
        explanation: `${num} rounded to the nearest ${unit} is ${rounded}.`,
      };
    }

    // 7. General Arithmetic via verifyArithmetic
    const directMath = this.verifyArithmetic(combined);
    if (directMath !== null) {
      const studentMatch = promptOrQuery.match(/(?:is\s+it\s+|answer\s+is\s+)?(-?\d+(?:\.\d+)?(?:\/\d+)?)/i);
      const studentAns = studentMatch ? studentMatch[1] : null;
      const isCorrect = studentAns !== null && (studentAns === directMath || Math.abs(parseFloat(studentAns) - parseFloat(directMath)) < 0.001);

      return {
        isMath: true,
        groundTruth: directMath,
        steps: [`Calculated deterministically according to UK National Curriculum arithmetic rules: ${directMath}`],
        explanation: `The exact mathematical result is ${directMath}.`,
        isStudentCorrect: studentAns !== null ? isCorrect : undefined,
      };
    }

    return null;
  }

  /**
   * Safe, deterministic token-based arithmetic evaluator for BIDMAS / PEMDAS expressions.
   * Does NOT use eval().
   */
  private static safeEvaluateBIDMAS(expr: string): number | null {
    try {
      const sanitized = expr.replace(/\s+/g, '');
      if (!/^[0-9\.\+\-\*\/\(\)]+$/.test(sanitized)) return null;

      // Tokenize
      const tokens: string[] = [];
      let current = '';
      for (let i = 0; i < sanitized.length; i++) {
        const c = sanitized[i];
        if (/[0-9\.]/.test(c)) {
          current += c;
        } else if ('+-*/()'.includes(c)) {
          if (current) {
            tokens.push(current);
            current = '';
          }
          // Check unary minus
          if (c === '-' && (tokens.length === 0 || '(*+/-'.includes(tokens[tokens.length - 1]))) {
            current = '-';
          } else {
            tokens.push(c);
          }
        }
      }
      if (current) tokens.push(current);

      // Shunting-yard algorithm to Reverse Polish Notation (RPN)
      const outputQueue: string[] = [];
      const opStack: string[] = [];
      const precedence: Record<string, number> = { '+': 1, '-': 1, '*': 2, '/': 2 };

      for (const token of tokens) {
        if (!isNaN(Number(token))) {
          outputQueue.push(token);
        } else if ('+-*/'.includes(token)) {
          while (
            opStack.length > 0 &&
            opStack[opStack.length - 1] !== '(' &&
            precedence[opStack[opStack.length - 1]] >= precedence[token]
          ) {
            outputQueue.push(opStack.pop()!);
          }
          opStack.push(token);
        } else if (token === '(') {
          opStack.push(token);
        } else if (token === ')') {
          while (opStack.length > 0 && opStack[opStack.length - 1] !== '(') {
            outputQueue.push(opStack.pop()!);
          }
          if (opStack.pop() !== '(') return null; // Mismatched parentheses
        }
      }

      while (opStack.length > 0) {
        const op = opStack.pop()!;
        if (op === '(' || op === ')') return null;
        outputQueue.push(op);
      }

      // Evaluate RPN
      const evalStack: number[] = [];
      for (const token of outputQueue) {
        if (!isNaN(Number(token))) {
          evalStack.push(Number(token));
        } else {
          if (evalStack.length < 2) return null;
          const b = evalStack.pop()!;
          const a = evalStack.pop()!;
          switch (token) {
            case '+': evalStack.push(a + b); break;
            case '-': evalStack.push(a - b); break;
            case '*': evalStack.push(a * b); break;
            case '/':
              if (b === 0) return null;
              evalStack.push(a / b);
              break;
            default: return null;
          }
        }
      }

      return evalStack.length === 1 ? evalStack[0] : null;
    } catch {
      return null;
    }
  }

  /**
   * Governs an incoming AST node tree against schema, logic, and topic constraints.
   */
  public static govern(
    raw: RawASTQuestion | null,
    expectedSubject: string,
    expectedTopic: string
  ): GovernedQuestion {
    // 1. Absolute Fallback: Generate valid topic question if AST is missing or contains placeholder tokens
    if (!raw || !raw.prompt || raw.prompt.includes('<STEM>') || !Array.isArray(raw.options)) {
      return {
        isValid: true,
        sanitizedQuestion: {
          id: `gov_${Date.now()}`,
          route: 'quiz:mcq',
          scratchpad: `Foundational knowledge check for ${expectedTopic}.`,
          prompt: `Which of the following is an accurate feature of ${expectedTopic} in ${expectedSubject}?`,
          options: [
            `Core observable patterns and standard rules of ${expectedTopic}`,
            `Conditions remain completely identical without variation`,
            `The foundational principles change randomly at each step`,
            `No distinct characteristics can be identified for ${expectedTopic}`
          ],
          answerKey: 0,
          hint: `Consider how ${expectedTopic} is structured in ${expectedSubject}.`
        },
      };
    }

    // 2. Sanitize and clean raw prompt stem
    let cleanPrompt = this.sanitizePromptText(String(raw.prompt || ''));
    if (!cleanPrompt || cleanPrompt.length < 5) {
      cleanPrompt = `Which statement correctly describes ${expectedTopic}?`;
    }

    // 3. Distractor De-duplication & Syntax Scrubbing
    const cleanedOptions = (raw.options || [])
      .map((opt) => {
        let text = String(opt || '').trim();
        // Remove option prefixes like "A)", "1.", "(B)"
        text = text.replace(/^[\(\[]?[A-Da-d1-4][\)\]\.\:\-\s]+\s*/, '');
        // Strip escaped slashes and quotes
        text = text.replace(/^\\+/, '').replace(/^"+|"+$/g, '').trim();
        return text;
      })
      .filter((opt) => {
        const lower = opt.toLowerCase();
        if (opt.length <= 1 || opt === '\\' || opt === '/') return false;
        if (lower.includes('said amelia') || lower.includes('said tom')) return false;
        if (
          lower.includes('all of the above') ||
          lower.includes('none of the above') ||
          lower.includes('all of these') ||
          lower.includes('none of these')
        ) {
          return false;
        }
        if (opt.includes('<STEM>') || opt.includes('<DISTRACTOR') || opt.includes('<CORRECT>')) return false;
        return true;
      });

    // Enforce case-insensitive uniqueness
    const seenLower = new Set<string>();
    const uniqueOptions: string[] = [];

    for (const opt of cleanedOptions) {
      const lower = opt.toLowerCase();
      if (!seenLower.has(lower)) {
        seenLower.add(lower);
        uniqueOptions.push(opt);
      }
    }

    // 4. Distractor Auto-Repair: Pad to at least 4 valid options instead of rejecting
    const genericDistractors = [
      `Alternative condition specific to higher level stages of ${expectedTopic}`,
      `Conditions remain constant without any variation in ${expectedTopic}`,
      `The opposite of the expected pattern occurs in this case`,
      `This principle relates to other distinct topics in ${expectedSubject}`
    ];

    while (uniqueOptions.length < 4) {
      const padOption = genericDistractors[uniqueOptions.length % genericDistractors.length];
      if (!uniqueOptions.includes(padOption)) {
        uniqueOptions.push(padOption);
      } else {
        uniqueOptions.push(`Alternative possibility ${uniqueOptions.length + 1} for ${expectedTopic}`);
      }
    }

    // 5. Deterministic Arithmetic Correction
    let targetAnswerKey = typeof raw.answerKey === 'number' && raw.answerKey >= 0 && raw.answerKey < uniqueOptions.length
      ? raw.answerKey
      : 0;

    const evaluatedSolution = this.verifyArithmetic(cleanPrompt, raw.scratchpad);
    if (evaluatedSolution) {
      const matchedIdx = uniqueOptions.findIndex(opt => {
        const cleanedOpt = opt.trim().toLowerCase();
        const cleanedSol = evaluatedSolution.toLowerCase();
        if (cleanedOpt === cleanedSol) return true;
        const numOpt = parseFloat(cleanedOpt);
        const numSol = parseFloat(cleanedSol);
        return !isNaN(numOpt) && !isNaN(numSol) && numOpt === numSol;
      });

      if (matchedIdx !== -1) {
        targetAnswerKey = matchedIdx;
      } else {
        uniqueOptions[0] = evaluatedSolution;
        targetAnswerKey = 0;
      }
    }

    // 6. Misconception Alignment & Diagnostic Synthesis
    let misconceptions: string[] = [];
    if (Array.isArray(raw.misconceptions) && raw.misconceptions.length > 0) {
      misconceptions = uniqueOptions.map((opt, i) => {
        if (i === targetAnswerKey) {
          return raw.misconceptions?.[i] || `Correct! Accurately demonstrates understanding of ${expectedTopic}.`;
        }
        return (
          raw.misconceptions?.[i] ||
          `Common misconception: This choice confuses the foundational rules or properties of ${expectedTopic}.`
        );
      });
    } else {
      misconceptions = uniqueOptions.map((opt, i) => {
        if (i === targetAnswerKey) {
          return `Correct! Spot on with the core principles of ${expectedTopic}.`;
        }
        return `Common trap: Confuses standard conditions or rules in ${expectedTopic}. Remember to test against the core definition.`;
      });
    }

    // 7. Deterministic Option Shuffling (Fisher-Yates Anti-Bias Guard)
    // Ensures the correct answer is evenly distributed across A, B, C, D (indices 0..3)
    const paired = uniqueOptions.map((opt, i) => ({
      opt,
      misconception: misconceptions[i] || '',
      isCorrect: i === targetAnswerKey,
    }));

    // Fisher-Yates shuffle
    for (let i = paired.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const temp = paired[i];
      paired[i] = paired[j];
      paired[j] = temp;
    }

    const shuffledOptions = paired.map((p) => p.opt);
    const shuffledMisconceptions = paired.map((p) => p.misconception);
    const finalAnswerKey = paired.findIndex((p) => p.isCorrect);

    return {
      isValid: true,
      sanitizedQuestion: {
        id: `q_${Date.now()}`,
        route: raw.route || 'quiz:mcq',
        scratchpad: String(raw.scratchpad || ''),
        prompt: cleanPrompt,
        options: shuffledOptions,
        answerKey: finalAnswerKey >= 0 ? finalAnswerKey : 0,
        hint: (raw as any).hint?.trim() || `Think about the key definition of ${expectedTopic}.`,
        explanation: raw.explanation || `The correct answer aligns directly with curriculum principles for ${expectedTopic}.`,
        misconceptions: shuffledMisconceptions,
        socraticFollowUp: raw.socraticFollowUp || `Can you identify which rule or definition applies to ${expectedTopic}?`,
      },
    };
  }
}