// src/engine/astGovernor.ts

export interface RawASTQuestion {
  route?: string;
  scratchpad?: string;
  prompt: string;
  options: string[];
  answerKey: number;
}

export interface GovernedQuestion {
  isValid: boolean;
  sanitizedQuestion: RawASTQuestion | null;
  rejectionReason?: string;
}

/**
 * AST Flow Governor: Evaluates, verifies, and sanitizes generated AST trees.
 */
export class ASTFlowGovernor {
  /**
   * Sanitizes the question prompt to strip accidental distractor bleeds,
   * escaped newlines, and trailing choice labels generated by small models.
   */
  public static sanitizePromptText(rawPrompt: string): string {
    if (!rawPrompt) return '';
    return rawPrompt
      // Strip inline option sequences like "A) Oxygen B) Carbon C) Sodium D) Nitrogen"
      .replace(/\s+[A-Da-d1-4][\)\.:\-]\s+.*$/s, '')
      // Strip trailing choice patterns like ":\n\nA) 1\nB) 5..."
      .replace(/(:\s*)?(\\n|\r|\n)*[A-Da-d1-4][\)\.:\-].*$/s, '')
      // Strip any lingering escaped newlines
      .replace(/\\n/g, ' ')
      // Collapse redundant whitespace
      .replace(/\s+/g, ' ')
      .trim();
  }

  private static gcd(x: number, y: number): number {
    return !y ? x : this.gcd(y, x % y);
  }

  /**
   * Deterministic Fraction/Decimal/Arithmetic Solver
   */
  private static verifyArithmetic(rawPrompt: any, rawScratchpad: any = ''): string | null {
    const prompt = String(rawPrompt || '');
    const scratchpad = String(rawScratchpad || '');

    // 1. Decimal to simplest fraction (e.g. "0.6 as a fraction")
    const decToFracMatch = prompt.match(/([\d\.]+)\s+as\s+a\s+fraction/i);
    if (decToFracMatch) {
      const val = parseFloat(decToFracMatch[1]);
      if (!isNaN(val)) {
        const decParts = decToFracMatch[1].split('.');
        const decimalPlaces = decParts[1] ? decParts[1].length : 0;
        const denominator = Math.pow(10, decimalPlaces);
        const numerator = Math.round(val * denominator);

        const divisor = this.gcd(numerator, denominator);
        const simpNum = numerator / divisor;
        const simpDen = denominator / divisor;

        return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
      }
    }

    // 2. Fraction Multiplication: (a/b) * (c/d) or a/b * c/d
    const fracMulMatch = prompt.match(/\(?(\d+)\/(\d+)\)?\s*[\*xX×]\s*\(?(\d+)\/(\d+)\)?/);
    if (fracMulMatch) {
      const [, a, b, c, d] = fracMulMatch.map(Number);
      const numerator = a * c;
      const denominator = b * d;

      const divisor = this.gcd(numerator, denominator);
      const simpNum = numerator / divisor;
      const simpDen = denominator / divisor;

      return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
    }

    // 3. Fraction Addition / Subtraction: a/b +/- c/d
    const fracAddMatch = prompt.match(/\(?(\d+)\/(\d+)\)?\s*([\+\-])\s*\(?(\d+)\/(\d+)\)?/);
    if (fracAddMatch) {
      const [, a, b, op, c, d] = fracAddMatch;
      const numA = Number(a), denB = Number(b), numC = Number(c), denD = Number(d);
      const commonDenominator = denB * denD;
      const numerator = op === '+' 
        ? (numA * denD + numC * denB) 
        : (numA * denD - numC * denB);

      const divisor = this.gcd(Math.abs(numerator), commonDenominator);
      const simpNum = numerator / divisor;
      const simpDen = commonDenominator / divisor;

      return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
    }

    // 4. Decimal Division: e.g. "0.5/2"
    const decDivMatch = prompt.match(/([\d\.]+)\s*\/\s*(\d+)/);
    if (decDivMatch) {
      const decVal = parseFloat(decDivMatch[1]);
      const divisorVal = parseInt(decDivMatch[2], 10);
      
      if (!isNaN(decVal) && !isNaN(divisorVal) && divisorVal !== 0) {
        const decParts = decDivMatch[1].split('.');
        const decimalPlaces = decParts[1] ? decParts[1].length : 0;
        const factor = Math.pow(10, decimalPlaces);

        const intNum = Math.round(decVal * factor);
        const intDen = divisorVal * factor;

        const d = this.gcd(intNum, intDen);
        const simpNum = intNum / d;
        const simpDen = intDen / d;

        return simpDen === 1 ? `${simpNum}` : `${simpNum}/${simpDen}`;
      }
    }

    // 5. Decimal / Integer Arithmetic: e.g. "0.75 + 0.25"
    const basicMathMatch = prompt.match(/([\d\.]+)\s*([\+\-\*\/])\s*([\d\.]+)/);
    if (basicMathMatch) {
      const num1 = parseFloat(basicMathMatch[1]);
      const op = basicMathMatch[2];
      const num2 = parseFloat(basicMathMatch[3]);

      if (!isNaN(num1) && !isNaN(num2)) {
        let result: number | null = null;
        switch (op) {
          case '+': result = num1 + num2; break;
          case '-': result = num1 - num2; break;
          case '*': result = num1 * num2; break;
          case '/': result = num2 !== 0 ? num1 / num2 : null; break;
        }

        if (result !== null) {
          const fixedDecimals = Math.max(
            (basicMathMatch[1].split('.')[1] || '').length,
            (basicMathMatch[3].split('.')[1] || '').length
          );
          return fixedDecimals > 0 ? result.toFixed(fixedDecimals) : String(result);
        }
      }
    }

    // 6. Scratchpad fallback: "... = 1/3"
    if (scratchpad) {
      const padEqMatch = scratchpad.match(/=\s*([0-9\.\/%a-zA-Z\s]+)$/);
      if (padEqMatch) {
        return padEqMatch[1].trim();
      }
    }

    return null;
  }

  /**
   * Governs an incoming AST node tree against schema, logic, and topic constraints.
   */
  public static govern(
    raw: RawASTQuestion,
    expectedSubject: string,
    expectedTopic: string
  ): GovernedQuestion {
    // 1. Sanitize and clean raw prompt stem
    const cleanPrompt = this.sanitizePromptText(String(raw?.prompt || ''));

    // 2. Structural Schema Validation
    if (!cleanPrompt || !Array.isArray(raw?.options) || raw.options.length < 2) {
      return {
        isValid: false,
        sanitizedQuestion: null,
        rejectionReason: 'AST Schema Failure: Missing prompt or insufficient options',
      };
    }

    // 3. Distractor De-duplication & Collapse Guard
    const sanitizedOptions = Array.from(
      new Set(raw.options.map(opt => String(opt).trim()))
    ).filter(Boolean);

    // Reject if distractors collapsed into duplicates (e.g. 4x identical answers)
    if (sanitizedOptions.length < 3) {
      return {
        isValid: false,
        sanitizedQuestion: null,
        rejectionReason: `AST Distractor Collapse: Fewer than 3 unique options generated (${sanitizedOptions.length} unique found).`,
      };
    }

    // 4. Deterministic Arithmetic Correction
    let targetAnswerKey = typeof raw.answerKey === 'number' && raw.answerKey >= 0 && raw.answerKey < sanitizedOptions.length
      ? raw.answerKey
      : 0;

    const evaluatedSolution = this.verifyArithmetic(cleanPrompt, raw.scratchpad);
    if (evaluatedSolution) {
      const matchedIdx = sanitizedOptions.findIndex(opt => {
        const cleanedOpt = opt.trim().toLowerCase();
        const cleanedSol = evaluatedSolution.toLowerCase();
        if (cleanedOpt === cleanedSol) return true;
        const numOpt = parseFloat(cleanedOpt);
        const numSol = parseFloat(cleanedSol);
        return !isNaN(numOpt) && !isNaN(numSol) && numOpt === numSol;
      });

      if (matchedIdx !== -1) {
        targetAnswerKey = matchedIdx;
      } else {
        sanitizedOptions[0] = evaluatedSolution;
        targetAnswerKey = 0;
      }
    }

    // 5. Subject/Topic Keyword Heuristic Firewall
    const cleanSubject = String(expectedSubject || '').toLowerCase();
    const cleanTopic = String(expectedTopic || '').toLowerCase();
    const isMathSubject = /math|geometry|circle|trig/i.test(cleanSubject) || 
      /fraction|decimal|algebra|arithmetic|percentage|circle|theorem|equation|root/i.test(cleanTopic);

    // Match mathematical equations (e.g. "x + y =", "3 * 4", "solve for x") rather than simple digits
    const hasMathOperators = /\b(calculate|solve\s+for|fraction|numerator|denominator|hypotenuse|pythagoras|algebraic)\b|[\+\*\/=]\s*\d+/i.test(cleanPrompt);

    if (!isMathSubject && hasMathOperators && !cleanPrompt.toLowerCase().includes(cleanTopic)) {
      return {
        isValid: false,
        sanitizedQuestion: null,
        rejectionReason: `AST Topic Bleed: Detected pure mathematical arithmetic in non-math context.`,
      };
    }

    return {
      isValid: true,
      sanitizedQuestion: {
        route: raw.route || 'quiz:mcq',
        scratchpad: String(raw.scratchpad || ''),
        prompt: cleanPrompt,
        options: sanitizedOptions,
        answerKey: targetAnswerKey,
      },
    };
  }
}