/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: src/engine
 */

// 1. Direct Re-Exports
export * from './ast-loader';
export * from './astGovernor';
export * from './EdgeCognitiveEngine';
export * from './engineflow';
export * from './operational-language';
export * from './promptAstparser';

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: 'src/engine',
  timestamp: 1787937755193,
  totalModules: 6,
  exports: [
  {
    "name": "ASTNode",
    "isType": true,
    "sourceFile": "ast-loader"
  },
  {
    "name": "parseAST",
    "isType": false,
    "sourceFile": "ast-loader"
  },
  {
    "name": "resolveTopicAST",
    "isType": false,
    "sourceFile": "ast-loader"
  },
  {
    "name": "RawASTQuestion",
    "isType": true,
    "sourceFile": "astGovernor"
  },
  {
    "name": "GovernedQuestion",
    "isType": true,
    "sourceFile": "astGovernor"
  },
  {
    "name": "ASTFlowGovernor",
    "isType": false,
    "sourceFile": "astGovernor"
  },
  {
    "name": "runLocalInference",
    "isType": false,
    "sourceFile": "EdgeCognitiveEngine"
  },
  {
    "name": "InteractiveEdgeSandbox",
    "isType": false,
    "sourceFile": "EdgeCognitiveEngine"
  },
  {
    "name": "GenerationRequest",
    "isType": true,
    "sourceFile": "engineflow"
  },
  {
    "name": "EngineResult",
    "isType": true,
    "sourceFile": "engineflow"
  },
  {
    "name": "EngineFlow",
    "isType": false,
    "sourceFile": "engineflow"
  },
  {
    "name": "SupportedLanguage",
    "isType": true,
    "sourceFile": "operational-language"
  },
  {
    "name": "SUPPORTED_LANGUAGES",
    "isType": false,
    "sourceFile": "operational-language"
  },
  {
    "name": "DEFAULT_LANGUAGE",
    "isType": false,
    "sourceFile": "operational-language"
  },
  {
    "name": "LanguageSelector",
    "isType": false,
    "sourceFile": "operational-language"
  },
  {
    "name": "PromptInferenceParams",
    "isType": true,
    "sourceFile": "promptAstparser"
  },
  {
    "name": "PromptASTPreParser",
    "isType": false,
    "sourceFile": "promptAstparser"
  }
]
} as const;

export type FolderExportNames = 'ASTNode' | 'parseAST' | 'resolveTopicAST' | 'RawASTQuestion' | 'GovernedQuestion' | 'ASTFlowGovernor' | 'runLocalInference' | 'InteractiveEdgeSandbox' | 'GenerationRequest' | 'EngineResult' | 'EngineFlow' | 'SupportedLanguage' | 'SUPPORTED_LANGUAGES' | 'DEFAULT_LANGUAGE' | 'LanguageSelector' | 'PromptInferenceParams' | 'PromptASTPreParser';
