/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: src/hooks
 */

// 1. Direct Re-Exports
export * from './hookengine';
export * from './useCurriculumStandard';
export * from './useKnowledgestage';
export * from './useWebRTCNeuralBus';

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: 'src/hooks',
  timestamp: 1787937755214,
  totalModules: 4,
  exports: [
  {
    "name": "HOOKS_MANIFEST",
    "isType": false,
    "sourceFile": "hookengine"
  },
  {
    "name": "useCurriculumStandard",
    "isType": false,
    "sourceFile": "useCurriculumStandard"
  },
  {
    "name": "StagePayload",
    "isType": true,
    "sourceFile": "useKnowledgestage"
  },
  {
    "name": "useKnowledgeStage",
    "isType": false,
    "sourceFile": "useKnowledgestage"
  },
  {
    "name": "QuestionPayload",
    "isType": true,
    "sourceFile": "useWebRTCNeuralBus"
  },
  {
    "name": "useWebRTCNeuralBus",
    "isType": false,
    "sourceFile": "useWebRTCNeuralBus"
  }
]
} as const;

export type FolderExportNames = 'HOOKS_MANIFEST' | 'useCurriculumStandard' | 'StagePayload' | 'useKnowledgeStage' | 'QuestionPayload' | 'useWebRTCNeuralBus';
