// src/hooks/hooksengine.ts
/**
 * AUTOGENERATED HOOKS ENGINE
 */

// 1. Re-export all custom hooks and contracts
export * from './useCurriculumStandard';
export * from './useKnowledgeStage';
export * from './useWebRTCNeuralBus';

// 2. Runtime Reflection & Capability Graph
export const HOOKS_MANIFEST = {
  folder: 'src/hooks',
  timestamp: Date.now(),
  capabilities: [
    { name: 'useCurriculumStandard', type: 'state-syncer', description: 'Cross-tab local storage state for UK Oak vs International' },
    { name: 'useKnowledgeStage', type: 'db-cache', description: 'IndexedDB ephemeral key stage facts' },
    { name: 'useWebRTCNeuralBus', type: 'ipc-daemon', description: 'P2P WebRTC data-channel link to offline neural worker' },
  ],
} as const;