/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: src/components
 */

// 1. Direct Re-Exports
export * from './componentsFlow';
export * from './CurriculumSelector';
export * from './DynamicLessonViewer';
export * from './InteractiveEdgeSandbox';
export * from './NanoAssistantPanel';
export * from './NeuralLabCanvas';
export * from './QuestionCard';
export * from './SettingsModal';
export * from './SExprViewRenderer';

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: 'src/components',
  timestamp: 1787937755135,
  totalModules: 9,
  exports: [
  {
    "name": "FlowCurriculumState",
    "isType": true,
    "sourceFile": "componentsFlow"
  },
  {
    "name": "NanoSessionConfig",
    "isType": true,
    "sourceFile": "componentsFlow"
  },
  {
    "name": "GroundedContextResult",
    "isType": true,
    "sourceFile": "componentsFlow"
  },
  {
    "name": "ComponentsFlow",
    "isType": false,
    "sourceFile": "componentsFlow"
  },
  {
    "name": "CurriculumSelector",
    "isType": false,
    "sourceFile": "CurriculumSelector"
  },
  {
    "name": "DynamicLessonViewer",
    "isType": false,
    "sourceFile": "DynamicLessonViewer"
  },
  {
    "name": "InteractiveEdgeSandbox",
    "isType": false,
    "sourceFile": "InteractiveEdgeSandbox"
  },
  {
    "name": "TuringTutor",
    "isType": false,
    "sourceFile": "NanoAssistantPanel"
  },
  {
    "name": "NeuralLabCanvas",
    "isType": false,
    "sourceFile": "NeuralLabCanvas"
  },
  {
    "name": "QuestionCard",
    "isType": false,
    "sourceFile": "QuestionCard"
  },
  {
    "name": "SettingsModal",
    "isType": false,
    "sourceFile": "SettingsModal"
  },
  {
    "name": "SExprViewRenderer",
    "isType": false,
    "sourceFile": "SExprViewRenderer"
  }
]
} as const;

export type FolderExportNames = 'FlowCurriculumState' | 'NanoSessionConfig' | 'GroundedContextResult' | 'ComponentsFlow' | 'CurriculumSelector' | 'DynamicLessonViewer' | 'InteractiveEdgeSandbox' | 'TuringTutor' | 'NeuralLabCanvas' | 'QuestionCard' | 'SettingsModal' | 'SExprViewRenderer';
