// scripts/generate-folder-engines.ts
import fs from 'fs';
import path from 'path';
import ts from 'typescript';

const TARGET_FOLDERS = [
  'src/components',
  'src/lib',
  'src/engine',
  'src/hooks',
  'src/curriculum',
];

interface ExportMeta {
  name: string;
  isType: boolean;
  sourceFile: string;
}

function extractExports(filePath: string): ExportMeta[] {
  const code = fs.readFileSync(filePath, 'utf-8');
  const sourceFile = ts.createSourceFile(filePath, code, ts.ScriptTarget.Latest, true);
  const found: ExportMeta[] = [];
  const baseName = path.basename(filePath, path.extname(filePath));

  function visit(node: ts.Node) {
    if (ts.isFunctionDeclaration(node) && node.name && hasExportModifier(node)) {
      found.push({ name: node.name.text, isType: false, sourceFile: baseName });
    } else if (ts.isVariableStatement(node) && hasExportModifier(node)) {
      node.declarationList.declarations.forEach(d => {
        if (ts.isIdentifier(d.name)) {
          found.push({ name: d.name.text, isType: false, sourceFile: baseName });
        }
      });
    } else if (ts.isClassDeclaration(node) && node.name && hasExportModifier(node)) {
      found.push({ name: node.name.text, isType: false, sourceFile: baseName });
    } else if ((ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) && hasExportModifier(node)) {
      found.push({ name: node.name.text, isType: true, sourceFile: baseName });
    } else if (ts.isExportDeclaration(node) && node.exportClause && ts.isNamedExports(node.exportClause)) {
      node.exportClause.elements.forEach(el => {
        found.push({ name: el.name.text, isType: node.isTypeOnly, sourceFile: baseName });
      });
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return found;
}

function hasExportModifier(node: ts.Node): boolean {
  return !!(ts.getCombinedModifierFlags(node as ts.Declaration) & ts.ModifierFlags.Export);
}

export function generateFolderEngines() {
  for (const relFolder of TARGET_FOLDERS) {
    const fullFolder = path.join(process.cwd(), relFolder);
    if (!fs.existsSync(fullFolder)) continue;

    const files = fs.readdirSync(fullFolder).filter(
      f => (f.endsWith('.ts') || f.endsWith('.tsx')) && !f.startsWith('engine.') && !f.startsWith('index.')
    );

    const folderExports: ExportMeta[] = [];
    const reExportStatements: string[] = [];

    for (const file of files) {
      const filePath = path.join(fullFolder, file);
      const baseName = file.replace(/\.tsx?$/, '');
      const exports = extractExports(filePath);

      if (exports.length > 0) {
        folderExports.push(...exports);
        reExportStatements.push(`export * from './${baseName}';`);
      }
    }

    const engineFileContent = `/**
 * AUTOGENERATED FOLDER ENGINE - DO NOT EDIT MANUALLY
 * Scanned from: ${relFolder}
 */

// 1. Direct Re-Exports
${reExportStatements.join('\n')}

// 2. Runtime Capability & Discovery Reflection
export const FOLDER_MANIFEST = {
  folder: '${relFolder}',
  timestamp: ${Date.now()},
  totalModules: ${files.length},
  exports: ${JSON.stringify(folderExports, null, 2)}
} as const;

export type FolderExportNames = ${
      folderExports.length ? folderExports.map(e => `'${e.name}'`).join(' | ') : 'never'
    };
`;

    fs.writeFileSync(path.join(fullFolder, 'engine.ts'), engineFileContent, 'utf-8');
    console.log(`⚡ Compiled Folder Engine: ${relFolder}/engine.ts (${folderExports.length} exported capabilities)`);
  }
}

generateFolderEngines();