// AUTO-GENERATED BY scripts/generate-scenes-manifest.js
// DO NOT EDIT MANUALLY - Derived directly from controlled cartridge input directories

export type CartridgeType = 'Sim' | 'Slide' | 'App';

export interface ScenePresetOption {
  id: string;
  type: CartridgeType;
  label: string;
  stage: string;
}

export const PRESET_OPTIONS: ScenePresetOption[] = [
  {
    "id": "church-tour",
    "type": "Slide",
    "label": "Tour of a Catholic Church: Sacred Architecture & Sacred Spaces",
    "stage": "CATHOLIC LIFE"
  },
  {
    "id": "calculus-curves",
    "type": "Sim",
    "label": "Calculus: Tangent Slopes & Definite Integrals",
    "stage": "GCSE & A-LEVEL MATHS"
  },
  {
    "id": "kinetic-gas",
    "type": "Sim",
    "label": "Kinetic Gas Theory & Boyle's Law",
    "stage": "KS3/KS4 PHYSICS & CHEMISTRY"
  },
  {
    "id": "electric-circuits",
    "type": "Sim",
    "label": "💡 Electrical Circuits & Ohm's Law (V = I × R)",
    "stage": "KS2/KS3 PHYSICS"
  },
  {
    "id": "bodmas",
    "type": "Slide",
    "label": "BODMAS / BIDMAS: Forcefield Clamping & Area Physics",
    "stage": "KS2/KS3 MATHS"
  },
  {
    "id": "times-tables",
    "type": "Slide",
    "label": "Times Tables: 2D Array & Distributive Splitter",
    "stage": "KS1/KS2 MATHS"
  },
  {
    "id": "phonics-lab",
    "type": "App",
    "label": "Early Phonics: Sound Buttons & Blending Mat",
    "stage": "EYFS/KS1 ENGLISH"
  },
  {
    "id": "math-fishing",
    "type": "Sim",
    "label": "Math Pond: Number Bonds Fishing Game",
    "stage": "KS1/KS2 MATHS"
  },
  {
    "id": "mountain-elevation",
    "type": "Sim",
    "label": "Mountain Altitude: Elevation, Hypotenuse & Atmospheric Science",
    "stage": "KS2/KS3 MATHS & GEOGRAPHY"
  },
  {
    "id": "fish-tank",
    "type": "App",
    "label": "Aquarium Stress Benchmark: Vector Point & FPS Limiter",
    "stage": "BENCHMARK & STRESS LAB"
  },
  {
    "id": "fractions",
    "type": "Slide",
    "label": "Fractions: Why Common Denominators Rule",
    "stage": "KS2 MATHS"
  },
  {
    "id": "solar-system",
    "type": "Sim",
    "label": "Solar System: Heliocentric Planetary Motion",
    "stage": "KS3 SCIENCE"
  },
  {
    "id": "photosynthesis",
    "type": "Slide",
    "label": "Photosynthesis: The Green Solar Engine",
    "stage": "KS3 BIOLOGY"
  },
  {
    "id": "pythagoras",
    "type": "Sim",
    "label": "Pythagoras' Theorem (a² + b² = c²)",
    "stage": "KS3 GEOMETRY"
  },
  {
    "id": "water-cycle",
    "type": "Slide",
    "label": "Water Cycle: Continuous Earth Cycle",
    "stage": "KS2 GEOGRAPHY"
  },
  {
    "id": "atom",
    "type": "Sim",
    "label": "Atomic Structure: Bohr Electron Shells",
    "stage": "KS3 CHEMISTRY"
  },
  {
    "id": "velocity",
    "type": "Sim",
    "label": "Kinematics: Velocity & Distance-Time Vectors",
    "stage": "KS3 PHYSICS"
  },
  {
    "id": "dna-helix",
    "type": "Slide",
    "label": "Genetics: DNA Base Pairing & Transcription",
    "stage": "KS3 GENETICS"
  },
  {
    "id": "algebra-balance",
    "type": "Sim",
    "label": "⚖️ Algebraic Balance Scale: Preserving Equality (2x + 5 = 15)",
    "stage": "KS2/KS3 MATHS"
  },
  {
    "id": "languages",
    "type": "App",
    "label": "MFL & Polyglot Studio: Spanish, French & Latin",
    "stage": "KS2/KS3 MFL"
  },
  {
    "id": "shakespeare",
    "type": "Slide",
    "label": "The Globe Theatre: Shakespeare & Iambic Pentameter",
    "stage": "KS3/KS4 ENGLISH LITERATURE"
  }
];
